portifolio/urls.py
from django.urls import path
from . import views

app_name = 'portifolio'


urlpatterns = [
    path('', views.home, name="home"),
    path('manager/', views.manager, name="manager"),
    path('features/', views.features, name="features"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('blog/', views.blog, name="blog"),
    path('post/<int:id>/', views.post, name="post"),
    path('resume/', views.resume, name="resume"),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portifolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portifolio/models.py
from django.db import models
from django.contrib.auth.models import User


class Personal(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    age = models.IntegerField()
    marital_status = models.CharField(max_length=45)
    cover = models.ImageField(upload_to='portifolio/covers/%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_id = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.first_name


class Address(models.Model):
    street = models.CharField(max_length=45)
    number = models.CharField(max_length=45)
    neighborhood = models.CharField(max_length=45)
    city = models.CharField(max_length=45)
    state = models.CharField(max_length=45)
    zipcode = models.CharField(max_length=45)
    complement = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.street


class Contact(models.Model):
    type = models.CharField(max_length=45)
    descrption_contact = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.descrption_contact


class Complementary_Courses(models.Model):
    course = models.CharField(max_length=100)
    instituition = models.CharField(max_length=45)
    duration = models.IntegerField()
    mounth = models.CharField(max_length=45)
    year = models.IntegerField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.course


class Education(models.Model):
    university = models.CharField(max_length=45)
    academic_title = models.CharField(max_length=45)
    course = models.CharField(max_length=45)
    final_project_theme = models.CharField(max_length=200, null=True)
    file = models.FileField(upload_to='portifolio/covers/%Y/%m/%d/', null=True)
    initialized_at = models.DateField(auto_now=False)
    finished_at = models.DateField(auto_now=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.academic_title


class Experience(models.Model):
    company = models.CharField(max_length=45)
    positions = models.CharField(max_length=45)
    initialized_at = models.DateField(auto_now=False)
    finished_at = models.DateField(null=True, blank=True)
    reponsabilities = models.TextField()
    visible = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.company


class Interests(models.Model):
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.description


class Skills(models.Model):
    skill_name = models.CharField(max_length=45)
    visible_icon = models.BooleanField(True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.skill_name


class Workflow(models.Model):
    workflow_name = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)
    personal_id = models.ForeignKey(
        Personal, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.workflow_name


class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.TextField()
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

portifolio/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from portifolio.models import Personal, Education, Experience, Workflow, Complementary_Courses, Interests, Message  # noqa E501


def manager(request):
    return render(request, 'portifolio/pages/manager.html', context={
        'name': 'Heder Lopes',
        'title': 'Manager |',
    })


def home(request):
    return render(request, 'portifolio/pages/home.html', context={
        'name': 'Heder Lopes',
        'title': 'Home |',
    })


def features(request):
    return render(request, 'portifolio/pages/features.html', context={
        'name': 'Heder Lopes',
        'title': 'Features |',
    })


def contact(request):
    return render(request, 'portifolio/pages/contact.html', context={
        'name': 'Heder Lopes',
        'title': 'Contact |',

    })


def blog(request):
    blog = Message.objects.filter(
        is_published=True,
    ).order_by('created_at')
    return render(request, 'portifolio/pages/blog.html', context={
        'blog': blog,
        'title': 'Blog |',

    })


def post(request, id):
    post = get_object_or_404(Message.objects.filter(pk=id, is_published=True))
    return render(request, 'portifolio/pages/blog-view.html', context={
        'post': post,
        'title': 'Post |',

    })


def about(request):
    return render(request, 'portifolio/pages/about.html', context={
        'name': 'Heder Lopes',
        'title': 'About |',
    })


def resume(request):
    personal = Personal.objects.filter(id=1)
    education = Education.objects.all()
    experience = Experience.objects.filter(
        visible=True,
    ).order_by('-initialized_at')
    workflow = Workflow.objects.all()
    courses = Complementary_Courses.objects.all().order_by('-year', '-mounth')
    interests = Interests.objects.all()

    return render(request, 'portifolio/pages/resume.html', context={
        'resume': personal,
        'education': education,
        'experience': experience,
        'workflow': workflow,
        'courses': courses,
        'interests': interests,
        'title': 'Resume | Portfolio',

    })

portifolio/templates/portifolio/pages/about.html
{% extends "global/base.html" %}

{% block 'title' %}{{title}}{% endblock 'title' %}


{% block 'content'  %}
<section class="section">
  <div class="main-content">
    <h2>About</h2>
    <div class="about-content">

          <!-- Seção Sobre o Projeto -->
      <div class="container">
        <h3 class="text-dark">About the Project</h3>
        <p class="">
          This project was developed using the Django framework, known for its robustness and simplicity in creating web applications. The goal of the project was to create a platform for task management, with functionalities for creating, editing, and deleting tasks, as well as user authentication.
        </p>
      </div>

      <!-- Seção Etapas de Desenvolvimento -->
      <div class="container">
        <h3 class="text-dark">Development Stages</h3>
        <ul class="list-group-flush">
          <li class="list-group-item">
            <strong>Planejamento:</strong> Definição dos requisitos e escopo do projeto.
          </li>
          <li class="list-group-item">
            <strong>Configuração do Ambiente:</strong> Criação do ambiente virtual e instalação do Django.
          </li>
          <li class="list-group-item">
            <strong>Modelagem do Banco de Dados:</strong> Criação dos modelos e migrações para o banco de dados.
          </li>
          <li class="list-group-item">
            <strong>Desenvolvimento do Back-end:</strong> Implementação das views, URLs e lógica de negócios.
          </li>
          <li class="list-group-item">
            <strong>Desenvolvimento do Front-end:</strong> Criação das templates utilizando HTML, CSS e Bootstrap.
          </li>
          <li class="list-group-item">
            <strong>Testes:</strong> Execução de testes unitários e de integração.
          </li>
          <li class="list-group-item">
            <strong>Deploy:</strong> Implantação do projeto em um servidor de produção.
          </li>
        </ul>
      </div>

      <!-- Seção Tecnologias Utilizadas -->
      <div class="container">
        <h3 class="text-dark">Technologies Used</h3>
        <ul class="list-group-flush">
          <li class="list-group-item">
            <strong>Django:</strong> Framework web de alto nível para desenvolvimento rápido e limpo.
          </li>
          <li class="list-group-item">
            <strong>Bootstrap 5.3:</strong> Framework front-end para design responsivo e mobile-first.
          </li>
          <li class="list-group-item">
            <strong>SQLite:</strong> Banco de dados leve utilizado durante o desenvolvimento.
          </li>
          <li class="list-group-item">
            <strong>HTML5 e CSS3:</strong> Linguagens de marcação e estilo para criação das interfaces.
          </li>
          <li class="list-group-item">
            <strong>JavaScript:</strong> Linguagem de programação para adicionar interatividade.
          </li>
        </ul>
      </div>
    </div>
    
  </div>
</section>
{% endblock 'content'  %}

portifolio/templates/portifolio/pages/admin.html
{% extends "global/base.html" %}

{% block 'title' %}Administration | {% endblock 'title' %}


{% block 'content'  %}
<section class="section">  
  <div class="main-content">
    <h2 class="text-dark">Administration</h2>

    <div class="intro-contact">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus odio dolores voluptate expedita suscipit qui facilis reiciendis necessitatibus dolorem eos ex provident veniam, nesciunt harum quis quod ratione cumque. Aperiam!</p>
    </div>   

    <div class="contact-form">
      <fieldset class="form-grid">
        <legend>Dados</legend>
        <form class="">
          <div class="form-group" >
            <label for="first-name">First Name</label>
            <input type="text" name="ffirst-name" id="first-name" placeholder="First Name">
                      </div>
          <div class="form-group" >
             <label for="last-name">Last Name</label>
             <input type="text"  name="last-name" id="last-name" placeholder="Last Name">
          </div>
          <div class="form-group" >
            <label for="email">E-Mail</label>
            <input type="email"  name="email" id="email" placeholder="example@email.com">
         </div>
         <div class="form-group" >
          <label for="message">Message</label>
          <textarea  name="message" id="message"  cols="30" rows="5" placeholder="Your Message"></textarea>
       </div>
            <div class="form-group">
          <button type="submit" class="btn-submit">Submit</button>
          </div>
        </form>
      </fieldset>
      
    </div>
  </section>
  {% endblock 'content'  %}

portifolio/templates/portifolio/pages/blog-view.html
{% extends "global/base.html" %}

{% block 'title' %}{{title}}{% endblock 'title' %}
 
{% block 'content' %}
<section class="section">  
  <div class="main-content">
    <h2 class="text-dark">Posts</h2>

    <div class="intro-posts">
      <p>Did you like my website? I want to hear from you! If you have any suggestions for improvement, constructive criticism or simply want to share your experience, leave a comment below. Your opinion is very important to me!</p>
    </div>   

    <div class="contact-form">

        <div class="post-content">                  
          <!-- Post preview-->  
          {% include 'portifolio/partials/message.html' %}

          <!-- Pager-->
          <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
            
        </div>    
      
    </div>
  </section>
  {% endblock 'content'  %}

portifolio/templates/portifolio/pages/blog.html
{% extends "global/base.html" %}

{% block 'title' %}{{title}}{% endblock 'title' %}
 
{% block 'content' %}
<section class="section">  
  <div class="main-content">
    <h2 class="text-dark">Posts</h2>

    <div class="intro-posts">
      <p>Did you like my website? I want to hear from you! If you have any suggestions for improvement, constructive criticism or simply want to share your experience, leave a comment below. Your opinion is very important to me!</p>
    </div>   

    <div class="contact-form">

        <div class="post-content">                  
          <!-- Post preview-->  
           {% for post in blog  %}
           
           {% include 'portifolio/partials/message.html' %}
           
           {% endfor %}
         

          <!-- Pager-->
          <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
            
        </div>    
      
    </div>
  </section>
  {% endblock 'content'  %}

portifolio/templates/portifolio/pages/contact.html
{% extends "global/base.html" %}

{% block 'title' %}{{title}}{% endblock 'title' %}
 
{% block 'content' %}
<section class="section">  
  <div class="main-content">
    <h2 class="text-dark">Contacts</h2>

    <div class="intro-contact">
      <p>Did you like my website? I want to hear from you! If you have any suggestions for improvement, constructive criticism or simply want to share your experience, leave a comment below. Your opinion is very important to me!</p>
    </div>   

    <div class="contact-form">
      <fieldset class="form-grid">
        <legend>Contact us</legend>
        <form class="">
          <div class="form-group" >
            <label for="first-name">First Name</label>
            <input type="text" name="ffirst-name" id="first-name" placeholder="First Name">
                      </div>
          {% comment %} <div class="form-group" >
             <label for="last-name">Last Name</label>
             <input type="text"  name="last-name" id="last-name" placeholder="Last Name">
          </div> {% endcomment %}
          <div class="form-group" >
            <label for="email">E-Mail</label>
            <input type="email"  name="email" id="email" placeholder="example@email.com">
         </div>
         <div class="form-group" >
          <label for="email">Categorie</label>
                   
          <select name="categorie" id="categorie">
            <option class="option-title" value="">Select</option>
            <option class="option-select" value="">Sugestão</option>
            <option class="option-select" value="">Perguntas</option>
            <option class="option-select" value="">option 3</option>
            <option class="option-select" value="">option 4</option>
            <option class="option-select" value="">option 5</option>
          </select>
       </div>
         <div class="form-group" >
          <label for="message">Message</label>
          <textarea  name="message" id="message"  cols="30" rows="5" placeholder="Your Message"></textarea>
       </div>
            <div class="form-group">
          <button type="submit" class="btn-submit">Submit</button>
          </div>
        </form>
      </fieldset>
      
    </div>
  </section>
  {% endblock 'content'  %}

portifolio/templates/portifolio/pages/features.html
{% extends "global/base.html" %}

{% block 'title' %}{{title}}{% endblock 'title' %}
 
{% block 'content' %}
<section class="section">  
  <div class="main-content">
    <h2 class="text-dark">Features</h2>

 <div class="features-content">
 
  <div class="card-feature">
    <a href="#">
      <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-diagram-3" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M6 3.5A1.5 1.5 0 0 1 7.5 2h1A1.5 1.5 0 0 1 10 3.5v1A1.5 1.5 0 0 1 8.5 6v1H14a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0V8h-5v.5a.5.5 0 0 1-1 0V8h-5v.5a.5.5 0 0 1-1 0v-1A.5.5 0 0 1 2 7h5.5V6A1.5 1.5 0 0 1 6 4.5zM8.5 5a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5zM0 11.5A1.5 1.5 0 0 1 1.5 10h1A1.5 1.5 0 0 1 4 11.5v1A1.5 1.5 0 0 1 2.5 14h-1A1.5 1.5 0 0 1 0 12.5zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm4.5.5A1.5 1.5 0 0 1 7.5 10h1a1.5 1.5 0 0 1 1.5 1.5v1A1.5 1.5 0 0 1 8.5 14h-1A1.5 1.5 0 0 1 6 12.5zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm4.5.5a1.5 1.5 0 0 1 1.5-1.5h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z"/>
      </svg>
      <div>
        <h3 class="title-card-feature">diagrams</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-database" viewBox="0 0 16 16">
      <path d="M4.318 2.687C5.234 2.271 6.536 2 8 2s2.766.27 3.682.687C12.644 3.125 13 3.627 13 4c0 .374-.356.875-1.318 1.313C10.766 5.729 9.464 6 8 6s-2.766-.27-3.682-.687C3.356 4.875 3 4.373 3 4c0-.374.356-.875 1.318-1.313M13 5.698V7c0 .374-.356.875-1.318 1.313C10.766 8.729 9.464 9 8 9s-2.766-.27-3.682-.687C3.356 7.875 3 7.373 3 7V5.698c.271.202.58.378.904.525C4.978 6.711 6.427 7 8 7s3.022-.289 4.096-.777A5 5 0 0 0 13 5.698M14 4c0-1.007-.875-1.755-1.904-2.223C11.022 1.289 9.573 1 8 1s-3.022.289-4.096.777C2.875 2.245 2 2.993 2 4v9c0 1.007.875 1.755 1.904 2.223C4.978 15.71 6.427 16 8 16s3.022-.289 4.096-.777C13.125 14.755 14 14.007 14 13zm-1 4.698V10c0 .374-.356.875-1.318 1.313C10.766 11.729 9.464 12 8 12s-2.766-.27-3.682-.687C3.356 10.875 3 10.373 3 10V8.698c.271.202.58.378.904.525C4.978 9.71 6.427 10 8 10s3.022-.289 4.096-.777A5 5 0 0 0 13 8.698m0 3V13c0 .374-.356.875-1.318 1.313C10.766 14.729 9.464 15 8 15s-2.766-.27-3.682-.687C3.356 13.875 3 13.373 3 13v-1.302c.271.202.58.378.904.525C4.978 12.71 6.427 13 8 13s3.022-.289 4.096-.777c.324-.147.633-.323.904-.525"/>
    </svg>
    <div>
      <h3 class="title-card-feature">database</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-graph-up-arrow" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M0 0h1v15h15v1H0zm10 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4.9l-3.613 4.417a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61L13.445 4H10.5a.5.5 0 0 1-.5-.5"/>
    </svg>
    <div>
      <h3 class="title-card-feature">charts</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-table" viewBox="0 0 16 16">
      <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm15 2h-4v3h4zm0 4h-4v3h4zm0 4h-4v3h3a1 1 0 0 0 1-1zm-5 3v-3H6v3zm-5 0v-3H1v2a1 1 0 0 0 1 1zm-4-4h4V8H1zm0-4h4V4H1zm5-3v3h4V4zm4 4H6v3h4z"/>
    </svg>
    <div>
      <h3 class="title-card-feature">tables</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-images" viewBox="0 0 16 16">
      <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/>
      <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2M14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1M2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1z"/>
    </svg>
    <div>
      <h3 class="title-card-feature">gallery</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
      <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
      <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
    </svg>
    <div>
      <h3 class="title-card-feature">files</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-lock" viewBox="0 0 16 16">
      <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2M5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1"/>
    </svg>
    <div>
      <h3 class="title-card-feature">security</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>

  <div class="card-feature">
    <a href="#">
    <svg xmlns="http://www.w3.org/2000/svg" class="color-svg-feature" width="45" height="45" fill="currentColor" class="bi bi-clipboard-check-fill" viewBox="0 0 16 16">
      <path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5z"/>
      <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5zm6.854 7.354-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708.708"/>
    </svg>
    <div>
      <h3 class="title-card-feature">reports</h3>
      <p>Paragraph of text beneath the heading to explain the heading.</p>
    </div>
  </a>
  </div>
 </div>
</div>
</section>
{% endblock 'content'  %}

portifolio/templates/portifolio/pages/home.html
{% extends "global/base.html" %}

{% block 'title' %}{{ title }}{% endblock 'title' %}


{% block 'content'  %}
<section class="section">
  <div class="main-content home-content">
    <h2 class="title-home">Welcome!</h2>
    <p class="text-home">Welcome to my first project developed with Python and Django! This is a journey that started with the curiosity to explore the world of programming and the passion to create innovative solutions. With this website, I aim to share my knowledge and offer a unique experience to visitors.
    </p>
          <a href="/about" class="btn-vermais">About more...</a>       
  </div>
</section>
  {% endblock 'content'  %}
    
    

portifolio/templates/portifolio/partials/message.html
          <!-- Post preview-->
          
          <div class="post-preview">
                <a href="{% url "portifolio:post" post.id %}">
                    <h3 class="post-title">{{ post.name }}</h3>
                    <p class="post-subtitle">{{ post.message }}.</p>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">{{ b.email }}</a>
                    on {{ post.created_at }} {{ post.id }}
                </p>
         </div>
        <!-- Divider-->
        <hr class="my-4">
       